name: 'Obsidian to Hugo Page Bundle'
description: 'A GitHub Action that extracts Obsidian Vault content, and transforms it to Hugo Page Bundles.'
inputs:
  obsidian-vault-dir:
    description: 'Directory of the Obsidian vault'
    required: true
    default: "vault"
  hugo-content-dir:
    description: 'Directory of your Hugo content directory, the obsidian notes should be processed into.'
    required: true
    default: "content"
  export-dir:
    description: 'The Obsidian vault folder the notes should be processed from.'
    required: true
    default: "vault"

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    # - name: Pass Inputs to Shell
    #   run: |
    #    echo "INPUT_NUM=${{ inputs.num }}" >> $GITHUB_ENV
    #   shell: bash
    - name: Run the Python Script
      shell: bash
      id: obsidian2hugo
      run: python src/main.py --obsidian-vault-dir ${{ inputs.obsidian-vault-dir }} --hugo-content-dir ${{ inputs.hugo-content-dir }} --export-dir ${{ inputs.export-dir }}